name = "my-todo-app"
compatibility_date = "2024-01-01"

[build]
command = "npm ci && npm run build"
pages_build_output_dir = "dist"

[env.production]
name = "my-todo-app-prod"

[env.staging]
name = "my-todo-app-staging" 