name = "my-todo-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "dist"

[site]
bucket = "./dist"
entry-point = "."

[env.production]
name = "my-todo-app-prod"

[env.staging]
name = "my-todo-app-staging" 