name = "my-todo-app"
compatibility_date = "2024-01-01"

[build]
command = "npm install && npm run build"
dist = "./dist"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"
entry-point = "."

# This is the key property Cloudflare Pages needs
pages_build_output_dir = "dist"

[env.production]
name = "my-todo-app-prod"

[env.staging]
name = "my-todo-app-staging" 